"""
####  3n + 1 Problem (Collatz Conjecture)  ####

A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:
___
*) If even: divide by 2.
*) If odd: multiply by 3, then add 1.
___

The Collatz algorithm has been tested and found to always reach 1 for all positive integers.
Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.


[Examples]

___
collatz(10, 15) ➞ "a"
# Because 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 6 steps
# 15.0 - 46.0 - 23.0 - 70.0 - 35.0 - 106.0 - 53.0 - 160.0 - 80.0 - 40.0 - 20.0 - 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 17 steps

collatz(13, 16) ➞ "b"

collatz(53782, 72534) ➞ "b"
_____



[Notes]

Assume a and b never take the same number of steps to reach 1.


[loops] [numbers] 



-------------------------------------------------------------------
[Resources]
_________
Collatz conjecture
https://en.wikipedia.org/wiki/Collatz_conjecture#:~:text=The%20Collatz%20conjecture%20is%20a,half%20of%20the%20previous%20term.
Is a conjecture in mathematics that concerns a sequence defined as follows: start with any positive integer n. Then each term is obtained from the previous term as foll …
_________
_________
Collatz Program
https://stackoverflow.com/questions/33508034/making-a-collatz-program-automate-the-boring-stuff
I'm trying to write a Collatz program using the guidelines from a project found at the end of chapter 3 of Automate the Boring Stuff with Python. I'm using python 3.4.0 …
_________
_________
Ternary Operator
https://careerkarma.com/blog/python-ternary-operator/
Is a conditional expression that executes code depending on whether a condition is true or false.
_________
_________
For Loops
https://www.w3schools.com/python/python_for_loops.asp
Is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). This is less like the for keyword in other programming langua …
_________
_________
Conditions
https://www.w3schools.com/python/python_conditions.asp
Python supports the usual logical conditions from mathematics. These conditions can be used in several ways, most commonly in "if statements" and loops.
_________

"""
#Your code should go here:

