"""
####  Fast Fibonacci  ####

In mathematics, the Fibonacci numbers, commonly denoted Fn, form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones, starting from 0 and 1:

and

for n > 1
The beginning of the sequence is thus:
___
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
_____

The function fib_fast(num) returns the fibonacci number Fn, of the given num as an argument.


[Examples]

___
fib_fast(5) ➞ 5

fib_fast(10) ➞ 55

fib_fast(20) ➞ 6765

fib_fast(50) ➞ 12586269025
_____



[Notes]

___
*) The input number is always positive.
*) Edabit would fail your code if it's not Fast enough.
___



[algorithms] [loops] [math] 



-------------------------------------------------------------------
[Resources]
_________
Fast Fibonacci Algorithms
https://www.nayuki.io/page/fast-fibonacci-algorithms
If we want to compute a single term in the sequence (e.g. F(n)), there are a couple of algorithms to do so. Some algorithms are much faster than others.
_________
_________
The General Term of Fibonacci Sequence
https://mathlibra.com/the-general-term-of-fibonacci-sequence/
In some cases, an arrangement of numbers such as 1, 1, 2, 3, 5, 8, … has no visible pattern, but the sequence is generated by the recurrence relation given by...
_________
_________
Fibonacci Sequence
https://en.wikipedia.org/wiki/Fibonacci_number
In mathematics, the Fibonacci numbers, commonly denoted Fn, form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones, …
_________
_________
Binet's Fibonacci Number Formula
https://mathworld.wolfram.com/BinetsFibonacciNumberFormula.html
Includes the formula and explanation of Binet's Fibonacci number formula.
_________

"""
#Your code should go here:

